### ISSUE TITLE
Remove the deprecated `debug` references

### ISSUE THREAD

**Issue by Rdbaker** [Asymmetrik/kyruus-node-sdk#5]
Hi guys,

A little while ago, we deprecated the `debug` flag in the API. Because of this, the `k.debug` and `k.removeDebug` methods are effectively no-ops. Might be good to clean up dead code :)

**Comment by andrewmarcus** [comment]
Hi @Rdbaker, thanks for letting us know!

**Comment by andrewmarcus** [comment]
Merged!
